---
- hosts:
  - dev
  - pro
  roles:
  - letsencrypt.yaml
  become: yes
  vars:
    doc_root: /services/kom-inn/admin-root
    server_name: "{{ admin_domain }}"
    server_alias: admin.kom-inn.org admin.dev.kom-inn.org
    basic_auth_file: /services/htpasswd_admins
  tasks:
  - name: Set up Apache virtual host file
    template: src=../templates/vhost.tpl dest=/etc/apache2/sites-enabled/001-admin.conf
    notify: restart apache
  - name: Ensure passwd file is present
    file: path=/services/htpasswd_admins state=touch
  - name: setup ssl certificates
    shell: "{{ item }}"
    with_items:
      - letsencrypt --apache -d {{ admin_domain }} -m sgulseth@gmail.com --non-interactive --agree-tos --redirect
      - chown -R root:letsencrypt /etc/letsencrypt
      - sudo chmod --recursive 755 /etc/letsencrypt
    notify: restart apache
  handlers:
  - name: restart apache
    service: name=apache2 state=restarted