---
- hosts:
  - dev
  - pro
  become: yes
  tasks:
  - name: install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
    - git
    - mcrypt
    - apache2
    - php7.0
    - php7.0-cli
    - php7.0-curl
    - php7.0-json
    - php7.0-mcrypt
    - php7.0-mysql
    - libapache2-mod-php7.0
    - composer
    - python-letsencrypt-apache

  - name: enable php apache module
    shell: a2enmod php7.0
    notify: restart apache
  - name: enable rewrite apache module
    shell: a2enmod rewrite
    notify: restart apache
  - name: remove default vhost
    file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
    notify: restart apache
  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
