---
- hosts:
  - dev
  - pro
  roles:
    - apache.yaml
  tasks:
  - name: Deploy
    git: repo=https://github.com/lars-raaum/kom-inn dest=/services/kom-inn force=True version=0.7.0
  - name: install web api php dependencies
    shell: composer install
    args:
      chdir: /services/kom-inn/web-api/
  - name: install admin api php dependencies
    shell: composer install
    args:
      chdir: /services/kom-inn/admin-api/
  - name: install cron php dependencies
    shell: composer install
    args:
      chdir: /services/kom-inn/crons/
  - name: setup cronjob for sending emails
    cron: name="emails" minute="0" hour="8" user="deploy" job="php /services/kom-inn/crons/stale_matches.php > /var/log/kom-inn/stale_matches.log"
  - name: setup cronjob for purging inactive
    cron: name="purge" minute="0" hour="9" user="deploy" job="php /services/kom-inn/crons/purge_inactive.php > /var/log/kom-inn/purge_inactive.log"
