---
- hosts:
  - dev
  - pro
  become: yes
  tasks:
  - name: install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
    - python-letsencrypt-apache
  - name: setup letsencrypt group
    group: name=letsencrypt state=present
  - name: setup www-data letsencrypt permissions
    user: name=www-data groups=devs,letsencrypt append=yes
  - name: enable ssl
    shell: a2enmod ssl
  - name: setup ssl certificates
    shell: chmod --recursive 755 /etc/letsencrypt
    notify: restart apache
  - name: setup cronjob for letsencrypt renewal
    cron: name="update certificates" minute="4" hour="0" user="root" job="letsencrypt renew > /var/log/letsencrypt-renewal.log && systemctl reload apache2"
  handlers:
  - name: restart apache
    service: name=apache2 state=restarted