---
- hosts:
  - dev
  - pro
  become: true
  tasks:
  - name: setup deploy user
    user: name=deploy comment="Deploy user" uid=1003 group=devs
  - name: authorized key for sguleth
    authorized_key: user=deploy key=https://github.com/sgulseth.keys
  - name: authorized key for alkemann
    authorized_key: user=deploy key=https://github.com/alkemann.keys
  - name: authorized key for jimbo
    authorized_key: user=deploy key=https://github.com/jimbofreedman.keys
