---
- hosts:
  - dev
  - pro
  become: yes
  vars:
    doc_root: /services/kom-inn/web-root
    server_name: "{{ web_domain }}"
    server_alias: kom-inn.org dev.kom-inn.org
  tasks:
  - name: Set up Apache virtual host file
    template: src=../templates/vhost.tpl dest=/etc/apache2/sites-enabled/000-web.conf
  - name: setup letsencrypt group
    group: name=letsencrypt state=present
  - name: setup www-data letsencrypt permissions
    user: name=www-data groups=devs,letsencrypt append=yes
  - name: enable ssl
    shell: a2enmod ssl
  - name: setup ssl certificates
    shell: "{{ item }}"
    with_items:
      - letsencrypt --apache -d {{ web_domain }} -m sgulseth@gmail.com --non-interactive --agree-tos --redirect
      - chown -R root:letsencrypt /etc/letsencrypt
      - sudo chmod --recursive 755 /etc/letsencrypt
    notify: restart apache
  - name: setup cronjob for letsencrypt renewal
    cron: name="update certificates" minute="4" hour="0" user="www-data" job="letsencrypt renew > /var/log/letsencrypt-renewal.log"
  handlers:
  - name: restart apache
    service: name=apache2 state=restarted